[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "magicgap"
version = "0.1.0"
dependencies = ["numpy", "scipy", "matplotlib", "jax", "argparse"]